version: "3"
services:
  native:
    image: nardzhiev/servernardzhiev
    hostname: NATIVE
    expose:
      - 10000/udp
    environment:
      - HOST=NATIVE
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  xml:
    image: nardzhiev/servernardzhiev
    hostname: XML
    expose:
      - 10000/udp
    environment:
      - HOST=XML
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  json:
    image: nardzhiev/servernardzhiev
    hostname: JSON
    expose:
      - 10000/udp
    environment:
      - HOST=JSON
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  gpb:
    image: nardzhiev/servernardzhiev
    hostname: GPB
    expose:
      - 10000/udp
    environment:
      - HOST=GPB
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  apache:
    image: nardzhiev/servernardzhiev
    hostname: APACHE
    expose:
      - 10000/udp
    environment:
      - HOST=APACHE
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  yaml:
    image: nardzhiev/servernardzhiev
    hostname: YAML
    expose:
      - 10000/udp
    environment:
      - HOST=YAML
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  msgpack:
    image: nardzhiev/servernardzhiev
    hostname: MSGPACK
    expose:
      - 10000/udp
    environment:
      - HOST=MSGPACK
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  client:
    image: nardzhiev/clientnardzhiev
    hostname: client
    expose:
      - 2000/udp
    ports:
      - "2000:2000/udp"
    environment:
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000
    depends_on:
      - native
      - xml
      - json
      - gpb
      - apache
      - yaml
      - msgpack
