version: "3"
services:
  native:
    build: server/
    hostname: NATIVE
    expose:
      - 10000/udp
    environment:
      - HOST=NATIVE
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  xml:
    build: server/
    hostname: XML
    expose:
      - 10000/udp
    environment:
      - HOST=XML
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  json:
    build: server/
    hostname: JSON
    expose:
      - 10000/udp
    environment:
      - HOST=JSON
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  gpb:
    build: server/
    hostname: GPB
    expose:
      - 10000/udp
    environment:
      - HOST=GPB
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  apache:
    build: server/
    hostname: APACHE
    expose:
      - 10000/udp
    environment:
      - HOST=APACHE
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  yaml:
    build: server/
    hostname: YAML
    expose:
      - 10000/udp
    environment:
      - HOST=YAML
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  msgpack:
    build: server/
    hostname: MSGPACK
    expose:
      - 10000/udp
    environment:
      - HOST=MSGPACK
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000

  client:
    build: client/
    hostname: client
    environment:
      - MULTICAST_ADDR=224.3.29.71
      - PORT=10000
    depends_on:
      - native
      - xml
      - json
      - gpb
      - apache
      - yaml
      - msgpack
