version: "3"
services:
  native:
    build: server/
    hostname: NATIVE
    expose:
      - 4001/udp
    environment:
      - HOST=NATIVE
      - PORT=4001

  xml:
    build: server/
    hostname: XML
    expose:
      - 4001/udp
    environment:
      - HOST=XML
      - PORT=4001

  json:
    build: server/
    hostname: JSON
    expose:
      - 4001/udp
    environment:
      - HOST=JSON
      - PORT=4001

  gpb:
    build: server/
    hostname: GPB
    expose:
      - 4001/udp
    environment:
      - HOST=GPB
      - PORT=4001

  apache:
    build: server/
    hostname: APACHE
    expose:
      - 4001/udp
    environment:
      - HOST=APACHE
      - PORT=4001

  yaml:
    build: server/
    hostname: YAML
    expose:
      - 4001/udp
    environment:
      - HOST=YAML
      - PORT=4001

  msgpack:
    build: server/
    hostname: MSGPACK
    expose:
      - 4001/udp
    environment:
      - HOST=MSGPACK
      - PORT=4001

  client:
    build: client/
    hostname: client
    environment:
      - PORT=4001
    depends_on:
      - native
      - xml
      - json
      - gpb
      - apache
      - yaml
      - msgpack
